-- MySQL Script generated by MySQL Workbench
-- Sun Sep 19 20:08:30 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema luckyStore
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema luckyStore
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `luckyStore` DEFAULT CHARACTER SET utf8 ;
USE `luckyStore` ;

-- -----------------------------------------------------
-- Table `luckyStore`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luckyStore`.`user` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `surname` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `role` VARCHAR(20) NULL DEFAULT NULL,
  `status` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id_user`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luckyStore`.`product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luckyStore`.`product` (
  `id_product` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NOT NULL,
  `price` DECIMAL NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `image` VARCHAR(150) NULL,
  PRIMARY KEY (`id_product`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luckyStore`.`cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luckyStore`.`cart` (
  `idcart` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  PRIMARY KEY (`idcart`),
  INDEX `fk_product_cart_idx` (`id_product` ASC) VISIBLE,
  INDEX `fk_user_cart_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_cart`
    FOREIGN KEY (`id_user`)
    REFERENCES `luckyStore`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_product_cart`
    FOREIGN KEY (`id_product`)
    REFERENCES `luckyStore`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luckyStore`.`transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luckyStore`.`transaction` (
  `id_transaction` INT NOT NULL AUTO_INCREMENT,
  `id_user` INT NOT NULL,
  `trans_amount` DECIMAL NOT NULL,
  `created_at` TIMESTAMP NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_transaction`),
  INDEX `fk_user_trans_idx` (`id_user` ASC) VISIBLE,
  CONSTRAINT `fk_user_trans`
    FOREIGN KEY (`id_user`)
    REFERENCES `luckyStore`.`user` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `luckyStore`.`order`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `luckyStore`.`order` (
  `id_order` INT NOT NULL AUTO_INCREMENT,
  `id_transaction` INT NOT NULL,
  `id_product` INT NOT NULL,
  `quantity` INT NOT NULL,
  `amount` DECIMAL NOT NULL,
  PRIMARY KEY (`id_order`),
  INDEX `fk_product_orders_idx` (`id_product` ASC) VISIBLE,
  INDEX `fk_trans_order_idx` (`id_transaction` ASC) VISIBLE,
  CONSTRAINT `fk_product_order`
    FOREIGN KEY (`id_product`)
    REFERENCES `luckyStore`.`product` (`id_product`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_trans_order`
    FOREIGN KEY (`id_transaction`)
    REFERENCES `luckyStore`.`transaction` (`id_transaction`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
